# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('auto_update_goal', models.BooleanField(default=True)),
                ('current_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in Inches', max_digits=5, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_activity_factor', models.DecimalField(blank=True, choices=[('1.2', 'Sedentary'), ('1.375', 'Lightly Active'), ('1.55', 'Moderately Active'), ('1.725', 'Very Active'), ('1.9', 'Extra Active')], decimal_places=3, max_digits=4, null=True)),
                ('current_daily_weight_goal', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('current_calorie_goal', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('C', 'Consumed (Eaten)'), ('E', 'Expended (Exercise)')], default='C', max_length=1)),
                ('calories', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_occurred', models.DateTimeField()),
                ('date', models.DateField()),
                ('bogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Bogger')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories_consumed', models.IntegerField(default=0)),
                ('calories_expended', models.IntegerField(default=0)),
                ('bogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Bogger')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in Inches', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('activity_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('bmr', models.IntegerField(blank=True, help_text='BMR', null=True)),
                ('daily_weight_goal', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('calorie_goal', models.IntegerField(blank=True, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('bogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Bogger')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together=set([('bogger', 'date')]),
        ),
    ]
