# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calorieentry',
            options={'get_latest_by': 'dt_occurred', 'verbose_name': 'Calorie Entry', 'verbose_name_plural': 'Calorie Entries'},
        ),
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'get_latest_by': 'date', 'verbose_name': 'Daily Entry', 'verbose_name_plural': 'Daily Entries'},
        ),
        migrations.AlterField(
            model_name='bogger',
            name='current_activity_factor',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary'), (1.375, 'Lightly Active'), (1.55, 'Moderately Active'), (1.725, 'Very Active'), (1.9, 'Extra Active')], null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='activity_factor',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary'), (1.375, 'Lightly Active'), (1.55, 'Moderately Active'), (1.725, 'Very Active'), (1.9, 'Extra Active')], null=True),
        ),
    ]
