# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20160603_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieentry',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 21, 10, 52, 995585)),
            preserve_default=False,
        ),
    ]
